use rust_bible_struct::{Bible, BibleBook};

mod common;
use common::test_utils;

const VERSE_CASES: &[(BibleBook, (usize, usize, &str), (usize, usize, &str))] = &[
    (BibleBook::Genesis, (1, 1, "In the beginning God created the heaven and the earth."), (50, 26, "So Joseph died, being an hundred and ten years old: and they embalmed him, and he was put in a coffin in Egypt.")),
    (BibleBook::Exodus, (1, 1, "Now these are the names of the children of Israel, which came into Egypt; every man and his household came with Jacob."), (40, 38, "For the cloud of the LORD was upon the tabernacle by day, and fire was on it by night, in the sight of all the house of Israel, throughout all their journeys.")),
    (BibleBook::Leviticus, (1, 1, "And the LORD called unto Moses, and spake unto him out of the tabernacle of the congregation, saying,"), (27, 34, "These are the commandments, which the LORD commanded Moses for the children of Israel in mount Sinai.")),
    (BibleBook::Numbers, (1, 1, "And the LORD spake unto Moses in the wilderness of Sinai, in the tabernacle of the congregation, on the first day of the second month, in the second year after they were come out of the land of Egypt, saying,"), (36, 13, "These are the commandments and the judgments, which the LORD commanded by the hand of Moses unto the children of Israel in the plains of Moab by Jordan near Jericho.")),
    (BibleBook::Deuteronomy, (1, 1, "These be the words which Moses spake unto all Israel on this side Jordan in the wilderness, in the plain over against the Red sea, between Paran, and Tophel, and Laban, and Hazeroth, and Dizahab. the Red...: or, Zuph"), (34, 12, "And in all that mighty hand, and in all the great terror which Moses shewed in the sight of all Israel.")),
    (BibleBook::Joshua, (1, 1, "Now after the death of Moses the servant of the LORD it came to pass, that the LORD spake unto Joshua the son of Nun, Moses' minister, saying,"), (24, 33, "And Eleazar the son of Aaron died; and they buried him in a hill that pertained to Phinehas his son, which was given him in mount Ephraim.")),
    (BibleBook::Judges, (1, 1, "Now after the death of Joshua it came to pass, that the children of Israel asked the LORD, saying, Who shall go up for us against the Canaanites first, to fight against them?"), (21, 25, "In those days there was no king in Israel: every man did that which was right in his own eyes.")),
    (BibleBook::Ruth, (1, 1, "Now it came to pass in the days when the judges ruled, that there was a famine in the land. And a certain man of Bethlehemjudah went to sojourn in the country of Moab, he, and his wife, and his two sons. "), (4, 22, "And Obed begat Jesse, and Jesse begat David.")),
    (BibleBook::FirstSamuel, (1, 1, "Now there was a certain man of Ramathaimzophim, of mount Ephraim, and his name was Elkanah, the son of Jeroham, the son of Elihu, the son of Tohu, the son of Zuph, an Ephrathite:"), (31, 13, "And they took their bones, and buried them under a tree at Jabesh, and fasted seven days.")),
    (BibleBook::SecondSamuel, (1, 1, "Now it came to pass after the death of Saul, when David was returned from the slaughter of the Amalekites, and David had abode two days in Ziklag;"), (24, 25, "And David built there an altar unto the LORD, and offered burnt offerings and peace offerings. So the LORD was intreated for the land, and the plague was stayed from Israel.")),
    (BibleBook::FirstKings, (1, 1, "Now king David was old and stricken in years; and they covered him with clothes, but he gat no heat. "), (22, 54, "For he served Baal, and worshipped him, and provoked to anger the LORD God of Israel, according to all that his father had done.")),
    (BibleBook::SecondKings, (1, 1, "Then Moab rebelled against Israel after the death of Ahab."), (25, 30, "And his allowance was a continual allowance given him of the king, a daily rate for every day, all the days of his life.")),
    (BibleBook::FirstChronicles, (1, 1, "Adam, Sheth, Enosh,"), (29, 30, "With all his reign and his might, and the times that went over him, and over Israel, and over all the kingdoms of the countries.")),
    (BibleBook::SecondChronicles, (1, 1, "And Solomon the son of David was strengthened in his kingdom, and the LORD his God was with him, and magnified him exceedingly."), (36, 23, "Thus saith Cyrus king of Persia, All the kingdoms of the earth hath the LORD God of heaven given me; and he hath charged me to build him an house in Jerusalem, which is in Judah. Who is there among you of all his people? The LORD his God be with him, and let him go up.")),
    (BibleBook::Ezra, (1, 1, "Now in the first year of Cyrus king of Persia, that the word of the LORD by the mouth of Jeremiah might be fulfilled, the LORD stirred up the spirit of Cyrus king of Persia, that he made a proclamation throughout all his kingdom, and put it also in writing, saying, "), (10, 44, "All these had taken strange wives: and some of them had wives by whom they had children.")),
    (BibleBook::Nehemiah, (1, 1, "The words of Nehemiah the son of Hachaliah. And it came to pass in the month Chisleu, in the twentieth year, as I was in Shushan the palace,"), (13, 31, "And for the wood offering, at times appointed, and for the firstfruits. Remember me, O my God, for good.")),
    (BibleBook::Esther, (1, 1, "Now it came to pass in the days of Ahasuerus, (this is Ahasuerus which reigned, from India even unto Ethiopia, over an hundred and seven and twenty provinces:)"), (10, 3, "For Mordecai the Jew was next unto king Ahasuerus, and great among the Jews, and accepted of the multitude of his brethren, seeking the wealth of his people, and speaking peace to all his seed.")),
    (BibleBook::Job, (1, 1, "There was a man in the land of Uz, whose name was Job; and that man was perfect and upright, and one that feared God, and eschewed evil."), (42, 17, "So Job died, being old and full of days.")),
    (BibleBook::Psalms, (1, 1, "Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful. "), (150, 6, "Let every thing that hath breath praise the LORD. Praise ye the LORD.")),
    (BibleBook::Proverbs, (1, 1, "The proverbs of Solomon the son of David, king of Israel;"), (31, 31, "Give her of the fruit of her hands; and let her own works praise her in the gates.")),
    (BibleBook::Ecclesiastes, (1, 1, "The words of the Preacher, the son of David, king in Jerusalem."), (12, 14, "For God shall bring every work into judgment, with every secret thing, whether it be good, or whether it be evil.")),
    (BibleBook::SongOfSolomon, (1, 1, "The song of songs, which is Solomon's."), (8, 14, "Make haste, my beloved, and be thou like to a roe or to a young hart upon the mountains of spices. ")),
    (BibleBook::Isaiah, (1, 1, "The vision of Isaiah the son of Amoz, which he saw concerning Judah and Jerusalem in the days of Uzziah, Jotham, Ahaz, and Hezekiah, kings of Judah."), (66, 24, "And they shall go forth, and look upon the carcases of the men that have transgressed against me: for their worm shall not die, neither shall their fire be quenched; and they shall be an abhorring unto all flesh.")),
    (BibleBook::Jeremiah, (1, 1, "The words of Jeremiah the son of Hilkiah, of the priests that were in Anathoth in the land of Benjamin:"), (52, 34, "And for his diet, there was a continual diet given him of the king of Babylon, every day a portion until the day of his death, all the days of his life. ")),
    (BibleBook::Lamentations, (1, 1, "How doth the city sit solitary, that was full of people! how is she become as a widow! she that was great among the nations, and princess among the provinces, how is she become tributary!"), (5, 22, "But thou hast utterly rejected us; thou art very wroth against us. ")),
    (BibleBook::Ezekiel, (1, 1, "Now it came to pass in the thirtieth year, in the fourth month, in the fifth day of the month, as I was among the captives by the river of Chebar, that the heavens were opened, and I saw visions of God. "), (48, 35, "It was round about eighteen thousand measures: and the name of the city from that day shall be, The LORD is there. The LORD...: Heb. Jehovahshammah")),
    (BibleBook::Daniel, (1, 1, "In the third year of the reign of Jehoiakim king of Judah came Nebuchadnezzar king of Babylon unto Jerusalem, and besieged it."), (12, 13, "But go thou thy way till the end be: for thou shalt rest, and stand in thy lot at the end of the days. for thou: or, and thou, etc")),
    (BibleBook::Hosea, (1, 1, "The word of the LORD that came unto Hosea, the son of Beeri, in the days of Uzziah, Jotham, Ahaz, and Hezekiah, kings of Judah, and in the days of Jeroboam the son of Joash, king of Israel."), (14, 9, "Who is wise, and he shall understand these things? prudent, and he shall know them? for the ways of the LORD are right, and the just shall walk in them: but the transgressors shall fall therein.")),
    (BibleBook::Joel, (1, 1, "The word of the LORD that came to Joel the son of Pethuel."), (3, 21, "For I will cleanse their blood that I have not cleansed: for the LORD dwelleth in Zion. for the...: or, even I the LORD that")),
    (BibleBook::Amos, (1, 1, "The words of Amos, who was among the herdmen of Tekoa, which he saw concerning Israel in the days of Uzziah king of Judah, and in the days of Jeroboam the son of Joash king of Israel, two years before the earthquake."), (9, 15, "And I will plant them upon their land, and they shall no more be pulled up out of their land which I have given them, saith the LORD thy God.")),
    (BibleBook::Obadiah, (1, 1, "The vision of Obadiah. Thus saith the Lord GOD concerning Edom; We have heard a rumour from the LORD, and an ambassador is sent among the heathen, Arise ye, and let us rise up against her in battle."), (1, 21, "And saviours shall come up on mount Zion to judge the mount of Esau; and the kingdom shall be the LORD'S.")),
    (BibleBook::Jonah, (1, 1, "Now the word of the LORD came unto Jonah the son of Amittai, saying, "), (4, 11, "And should not I spare Nineveh, that great city, wherein are more than sixscore thousand persons that cannot discern between their right hand and their left hand; and also much cattle?")),
    (BibleBook::Micah, (1, 1, "The word of the LORD that came to Micah the Morasthite in the days of Jotham, Ahaz, and Hezekiah, kings of Judah, which he saw concerning Samaria and Jerusalem."), (7, 20, "Thou wilt perform the truth to Jacob, and the mercy to Abraham, which thou hast sworn unto our fathers from the days of old.")),
    (BibleBook::Nahum, (1, 1, "The burden of Nineveh. The book of the vision of Nahum the Elkoshite."), (3, 19, "There is no healing of thy bruise; thy wound is grievous: all that hear the bruit of thee shall clap the hands over thee: for upon whom hath not thy wickedness passed continually? ")),
    (BibleBook::Habakkuk, (1, 1, "The burden which Habakkuk the prophet did see."), (3, 19, "The LORD God is my strength, and he will make my feet like hinds' feet, and he will make me to walk upon mine high places. To the chief singer on my stringed instruments.  ")),
    (BibleBook::Zephaniah, (1, 1, "The word of the LORD which came unto Zephaniah the son of Cushi, the son of Gedaliah, the son of Amariah, the son of Hizkiah, in the days of Josiah the son of Amon, king of Judah."), (3, 20, "At that time will I bring you again, even in the time that I gather you: for I will make you a name and a praise among all people of the earth, when I turn back your captivity before your eyes, saith the LORD.")),
    (BibleBook::Haggai, (1, 1, "In the second year of Darius the king, in the sixth month, in the first day of the month, came the word of the LORD by Haggai the prophet unto Zerubbabel the son of Shealtiel, governor of Judah, and to Joshua the son of Josedech, the high priest, saying,  "), (2, 23, "In that day, saith the LORD of hosts, will I take thee, O Zerubbabel, my servant, the son of Shealtiel, saith the LORD, and will make thee as a signet: for I have chosen thee, saith the LORD of hosts.")),
    (BibleBook::Zechariah, (1, 1, "In the eighth month, in the second year of Darius, came the word of the LORD unto Zechariah, the son of Berechiah, the son of Iddo the prophet, saying,"), (14, 21, "Yea, every pot in Jerusalem and in Judah shall be holiness unto the LORD of hosts: and all they that sacrifice shall come and take of them, and seethe therein: and in that day there shall be no more the Canaanite in the house of the LORD of hosts.")),
    (BibleBook::Malachi, (1, 1, "The burden of the word of the LORD to Israel by Malachi. "), (4, 6, "And he shall turn the heart of the fathers to the children, and the heart of the children to their fathers, lest I come and smite the earth with a curse.")),
    (BibleBook::Matthew, (1, 1, "The book of the generation of Jesus Christ, the son of David, the son of Abraham."), (28, 20, "Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen.")),
    (BibleBook::Mark, (1, 1, "The beginning of the gospel of Jesus Christ, the Son of God;"), (16, 20, "And they went forth, and preached every where, the Lord working with them, and confirming the word with signs following. Amen.")),
    (BibleBook::Luke, (1, 1, "Forasmuch as many have taken in hand to set forth in order a declaration of those things which are most surely believed among us,"), (24, 53, "And were continually in the temple, praising and blessing God. Amen.")),
    (BibleBook::John, (1, 1, "In the beginning was the Word, and the Word was with God, and the Word was God."), (21, 25, "And there are also many other things which Jesus did, the which, if they should be written every one, I suppose that even the world itself could not contain the books that should be written. Amen.")),
    (BibleBook::Acts, (1, 1, "The former treatise have I made, O Theophilus, of all that Jesus began both to do and teach,"), (28, 31, "Preaching the kingdom of God, and teaching those things which concern the Lord Jesus Christ, with all confidence, no man forbidding him.")),
    (BibleBook::Romans, (1, 1, "Paul, a servant of Jesus Christ, called to be an apostle, separated unto the gospel of God,"), (16, 27, "To God only wise, be glory through Jesus Christ for ever. Amen. «Written to the Romans from Corinthus, and sent by Phebe servant of the church at Cenchrea.»")),
    (BibleBook::FirstCorinthians, (1, 1, "Paul, called to be an apostle of Jesus Christ through the will of God, and Sosthenes our brother,"), (16, 24, "My love be with you all in Christ Jesus. Amen. «The first epistle to the Corinthians was written from Philippi by Stephanas and Fortunatus and Achaicus and Timotheus.»")),
    (BibleBook::SecondCorinthians, (1, 1, "Paul, an apostle of Jesus Christ by the will of God, and Timothy our brother, unto the church of God which is at Corinth, with all the saints which are in all Achaia:"), (13, 14, "The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all. Amen. «The second epistle to the Corinthians was written from Philippi, a city of Macedonia, by Titus and Lucas.»")),
    (BibleBook::Galatians, (1, 1, "Paul, an apostle, (not of men, neither by man, but by Jesus Christ, and God the Father, who raised him from the dead;)"), (6, 18, "Brethren, the grace of our Lord Jesus Christ be with your spirit. Amen. «To the Galatians written from Rome.»")),
    (BibleBook::Ephesians, (1, 1, "Paul, an apostle of Jesus Christ by the will of God, to the saints which are at Ephesus, and to the faithful in Christ Jesus:"), (6, 24, "Grace be with all them that love our Lord Jesus Christ in sincerity. Amen. «To the Ephesians written from Rome, by Tychicus.» in sincerity: or, with incorruption")),
    (BibleBook::Philippians, (1, 1, "Paul and Timotheus, the servants of Jesus Christ, to all the saints in Christ Jesus which are at Philippi, with the bishops and deacons:"), (4, 23, "The grace of our Lord Jesus Christ be with you all. Amen. «To the Philippians written from Rome, by Epaphroditus.»")),
    (BibleBook::Colossians, (1, 1, "Paul, an apostle of Jesus Christ by the will of God, and Timotheus our brother,"), (4, 18, "The salutation by the hand of me Paul. Remember my bonds. Grace be with you. Amen. «Written from Rome to Colossians by Tychicus and Onesimus.»")),
    (BibleBook::FirstThessalonians, (1, 1, "Paul, and Silvanus, and Timotheus, unto the church of the Thessalonians which is in God the Father and in the Lord Jesus Christ: Grace be unto you, and peace, from God our Father, and the Lord Jesus Christ."), (5, 28, "The grace of our Lord Jesus Christ be with you. Amen. «The first epistle to the Thessalonians was written from Athens.»")),
    (BibleBook::SecondThessalonians, (1, 1, "Paul, and Silvanus, and Timotheus, unto the church of the Thessalonians in God our Father and the Lord Jesus Christ:"), (3, 18, "The grace of our Lord Jesus Christ be with you all. Amen. «The second epistle to the Thessalonians was written from Athens.»")),
    (BibleBook::FirstTimothy, (1, 1, "Paul, an apostle of Jesus Christ by the commandment of God our Saviour, and Lord Jesus Christ, which is our hope;"), (6, 21, "Which some professing have erred concerning the faith. Grace be with thee. Amen. «The first to Timothy was written from Laodicea, which is the chiefest city of Phrygia Pacatiana.»")),
    (BibleBook::SecondTimothy, (1, 1, "Paul, an apostle of Jesus Christ by the will of God, according to the promise of life which is in Christ Jesus,"), (4, 22, "The Lord Jesus Christ be with thy spirit. Grace be with you. Amen. «The second epistle unto Timotheus, ordained the first bishop of the church of the Ephesians, was written from Rome, when Paul was brought before Nero the second time.»")),
    (BibleBook::Titus, (1, 1, "Paul, a servant of God, and an apostle of Jesus Christ, according to the faith of God's elect, and the acknowledging of the truth which is after godliness;"), (3, 15, "All that are with me salute thee. Greet them that love us in the faith. Grace be with you all. Amen. «It was written to Titus, ordained the first bishop of the church of the Cretians, from Nicopolis of Macedonia.»")),
    (BibleBook::Philemon, (1, 1, "Paul, a prisoner of Jesus Christ, and Timothy our brother, unto Philemon our dearly beloved, and fellowlabourer,"), (1, 25, "The grace of our Lord Jesus Christ be with your spirit. Amen. «Written from Rome to Philemon, by Onesimus a servant.»")),
    (BibleBook::Hebrews, (1, 1, "God, who at sundry times and in divers manners spake in time past unto the fathers by the prophets,"), (13, 25, "Grace be with you all. Amen. «Written to the Hebrews from Italy, by Timothy.»")),
    (BibleBook::James, (1, 1, "James, a servant of God and of the Lord Jesus Christ, to the twelve tribes which are scattered abroad, greeting."), (5, 20, "Let him know, that he which converteth the sinner from the error of his way shall save a soul from death, and shall hide a multitude of sins.")),
    (BibleBook::FirstPeter, (1, 1, "Peter, an apostle of Jesus Christ, to the strangers scattered throughout Pontus, Galatia, Cappadocia, Asia, and Bithynia,"), (5, 14, "Greet ye one another with a kiss of charity. Peace be with you all that are in Christ Jesus. Amen.")),
    (BibleBook::SecondPeter, (1, 1, "Simon Peter, a servant and an apostle of Jesus Christ, to them that have obtained like precious faith with us through the righteousness of God and our Saviour Jesus Christ:  "), (3, 18, "But grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ. To him be glory both now and for ever. Amen.")),
    (BibleBook::FirstJohn, (1, 1, "That which was from the beginning, which we have heard, which we have seen with our eyes, which we have looked upon, and our hands have handled, of the Word of life;"), (5, 21, "Little children, keep yourselves from idols. Amen.")),
    (BibleBook::SecondJohn, (1, 1, "The elder unto the elect lady and her children, whom I love in the truth; and not I only, but also all they that have known the truth;"), (1, 13, "The children of thy elect sister greet thee. Amen.")),
    (BibleBook::ThirdJohn, (1, 1, "The elder unto the wellbeloved Gaius, whom I love in the truth. "), (1, 15, "Peace be to thee. Our friends salute thee. Greet the friends by name. face to...: Gr. mouth to mouth")),
    (BibleBook::Jude, (1, 1, "Jude, the servant of Jesus Christ, and brother of James, to them that are sanctified by God the Father, and preserved in Jesus Christ, and called:"), (1, 25, "To the only wise God, our Saviour, be glory and majesty, dominion and power, both now and ever. Amen.")),
    (BibleBook::Revelation, (1, 1, "The Revelation of Jesus Christ, which God gave unto him, to shew unto his servants things which must shortly come to pass; and he sent and signified it by his angel unto his servant John:"), (22, 21, "The grace of our Lord Jesus Christ be with you all. Amen.")),
];

#[test]
fn test_first_and_last_verses_of_each_book() {
    let file_path = match test_utils::get_kjv_json() {
        Some(path) => path,
        None => {
            println!("Skipping test_first_and_last_verses_of_each_book: en_kjv.json not found");
            return;
        }
    };

    let bible = Bible::new_from_json(&file_path).expect("Failed to load Bible JSON");

    for (book, (f_ch, f_vs, f_text), (l_ch, l_vs, l_text)) in VERSE_CASES {
        let verse = bible
            .get_verse(*book, *f_ch, *f_vs)
            .expect(&format!("Missing first verse for {:?}", book));
        assert_eq!(format!("{}: {}", f_vs, f_text), format!("{}", verse));

        let verse = bible
            .get_verse(*book, *l_ch, *l_vs)
            .expect(&format!("Missing last verse for {:?}", book));
        assert_eq!(format!("{}: {}", l_vs, l_text), format!("{}", verse));
    }
}
